blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Ask a question or start a discussion
    url: https://github.com/KusoGames/Kuso-Physics/discussions
    about: Please ask and answer questions in GitHub Discussions.
